### ISSUE TITLE
https://learn-dev.nuxt.com/  show page not found

### ISSUE THREAD

**Issue by upthen** [nuxt/learn.nuxt.com#124]
Hi, Fu,

I'm afraid there is something wrong with this site https://learn-dev.nuxt.com/

I got "Page Not Found" tips when visited it.

Might you confirm that in your free time.

Well, take good care of yourself.
why not toke some photos in Spring, you have not update your Instagram for a long time. Make some time for relax!
Wish you best!

**Comment by antfu** [comment]
Should be fixed, thank you
