### ISSUE TITLE
feature: Collapse terminal panel 

### ISSUE THREAD

**Issue by rpiechowicz** [nuxt/learn.nuxt.com#26]
Small feature aiming to immediately show/hide the terminal
(This can be applied to all panels in the future)

https://github.com/nuxt/learn.nuxt.com/assets/48628592/5ec907bd-358a-4935-8a5c-96482990ff46

**Comment by antfu** [comment]
I was thinking of having an open and close button to now even showing the bar of Terminal. We might consider hide it by default later on, as when working with the tutorial users might not need to be distracted by a terminal.
