### ISSUE TITLE
Add a collapse icon in panel

### ISSUE THREAD

**Issue by zyyv** [nuxt/learn.nuxt.com#45]
Like this?
<img width="675" alt="image" src="https://github.com/nuxt/learn.nuxt.com/assets/42139754/1b4f1222-923f-4f82-b982-5bd0ed32993d">

**Comment by antfu** [comment]
While I am not against having it, I am not so sure how useful it is. Given that we are going to add the function to toggle the visibility of the terminal panel, meaning that under most of the scenario, we only have two panels Editor and Preview. Not sure when we want to hide Editor and only how Preview or vice versa.

**Comment by zyyv** [comment]
Yep, i understand your mean. I will close it, now `TerminalPanel` miss min-size,
