### ISSUE TITLE
Better file tree

### ISSUE THREAD

**Issue by stylessh** [nuxt/learn.nuxt.com#53]
I can create a PR for a better file tree with icons and depth levels

<img width="468" alt="Screenshot 2023-12-02 at 12 33 42" src="https://github.com/nuxt/learn.nuxt.com/assets/45767683/badaa7ba-9c44-4702-bf15-72bc6ec29d6e">

Any plans on doing that? :)

**Comment by antfu** [comment]
It's definitely on the plan, and we will do it on the stream
