### ISSUE TITLE
Add interactivity shell issues.

### ISSUE THREAD

**Issue by HoMeTownSoCool** [nuxt/learn.nuxt.com#66]
I found when i create a interactivity shell, i need create tow process make it work, one auto-start process, one interactive process, but now status is not ok for that, beacuse if the user presses Ctrl+C during installation, the previous state should be successful!
like this:
![image](https://github.com/nuxt/learn.nuxt.com/assets/47271407/1428f5ad-681a-46d7-a8af-4a794603c52c)

**Comment by antfu** [comment]
Should be fixed
