### ISSUE TITLE
When I clicked the guide to a new route, and then came back, the editor disapperared, and I could not click the files.

### ISSUE THREAD

**Issue by CherishTheYouth** [nuxt/learn.nuxt.com#69]
![Kapture 2023-12-07 at 23.20.14](https://cherish-1256678432.cos.ap-nanjing.myqcloud.com/typora/Kapture%202023-12-07%20at%2023.20.14.gif)

我在程序运行之后，编辑器可正常编辑代码，但是当我点击左边的指南里的任意一个路径，之后，编辑区消失了，只留下一片空白区域，我选中任意一个文件都没反应，程序似乎也变成终止状态了，这很奇怪，不知道这个 playground 的使用逻辑是啥。

**Comment by CherishTheYouth** [comment]
![Kapture 2023-12-07 at 23.20.14](https://cherish-1256678432.cos.ap-nanjing.myqcloud.com/typora/Kapture%202023-12-07%20at%2023.20.14-20231207233145295.gif)

https://cherish-1256678432.cos.ap-nanjing.myqcloud.com/typora/Kapture%202023-12-07%20at%2023.20.14-20231207233145295.gif

Seems something wrong with this editior,  the bigger size  gif could not show normally, just click the link for it.

**Comment by CherishTheYouth** [comment]
![image](https://github.com/nuxt/learn.nuxt.com/assets/41944818/f1451dc0-13f1-4476-9454-3731269b3c0b)

Some errors occurs in console.

**Comment by antfu** [comment]
Fixed
