### ISSUE TITLE
Video Indexed Summary

### ISSUE THREAD

**Issue by nick-wireless** [nuxt/learn.nuxt.com#84]
Hi Anthony,

I am a beginner hoping to learn basics of WebApp development by following along.

In doing so, I think I'll watch and rewatch the process to apply to some of my own projects.  For that, I've made a different kind of summary to link to your chapters and videos.  See [here](https://github.com/nick-wireless/learn.nuxt.com/blob/video2_start/readme_video2.md) for an example.

Do you think this is useful or a neusance if associated with your project?  Perhaps I should be makeing it better before publishing or putting it in a different section of github?

Let me know your leaning and I'll either stop or continue on.

Thanks.

**Comment by SSMM0498** [comment]
Hi, it's not my place to answer but I really appreciate the effort. I love this streaming series but sometimes I have trouble freeing myself to follow the streams (I have 2 episodes to catch up on). This will be very useful to me.

**Comment by antfu** [comment]
Oh that's awesome, I didn't expect this, thank you!

I think that it would be nice if you could start it as a repository under your name and put the content in README.md so ppl could read it better. And in that sense, I am happy to link to your summary of this project and could probably mention it on the next live.

Thank you for doing this!

**Comment by nick-wireless** [comment]
OK, I am a long way behind, so will get to where I get to and update this post when I'm kind of done.

**Comment by nick-wireless** [comment]
I streamlined a little by putting all in the one Readme.md, as you suggested.

My notes are a little higgldy piggldy.  I'm working out through the episodes how to be more consistent with the formatting and referencing, that said... it may help others and I hope to continue:

[QuickLink To Index Here](https://github.com/nick-wireless/learn.nuxt.com?tab=readme-ov-file)
